In [1]:
import numpy as np
import math

In [2]:
class node_class:
    def __init__(self, position,g,h,f,parent,Type):
        self.parent = parent
        self.position = position
        self.g =g 
        self.h =h
        self.f =f 
        self.type=Type

In [3]:
def successors(node):
    global Map
    List_successors=[]
    for i in -1,0,1:
        for j in -1,0,1:
            if Map[node.position[0]+i,node.position[1]+j]>0:
                List_successors.append(node_class([node.position[0]+i,node.position[1]+j],None,None,None,node,Map[node.position[0]+i,node.position[1]+j]))
    
    for node in List_successors:
        if node.position==node.parent:
            List_successors.remove(node) #remove the node itself
    return List_successors

In [4]:
class map:
    def __init__(self,position,Type):
        self.position = position
        self.type = Type

In [5]:
def distance(node,goal):
    return math.dist(node.position,goal.position)

In [6]:
def get_minimum(List):
    min_f_list=[]
    min_value_f=100
    min_value_h=100
    min_index=0
    for i in range(len(List)):
        if List[i].f < min_value_f:
            min_value_f=List[i].f
            min_index = i

    for i in range(len(List)):
        if List[i].f == min_value_f:
            min_f_list.append(i)

    for i in min_f_list:
        if List[i].h < min_value_h:
            min_value_h=List[i].h
            min_index = i
    return List[min_index],min_index

In [7]:
def A_star(start,goal):
    open_list = []
    closed_list = []
    open_list.append(start)

    while len(open_list) > 0:
        parent,index=get_minimum(open_list)
        open_list.pop(index)
        childern=successors(parent)

        for child in childern:
            if child.position == goal.position:
                goal.parent=parent
                return goal

        for child in childern:
            g_cost=parent.g+distance(parent,child)
            h_cost=distance(child,goal)
            f_cost=g_cost+h_cost
            child.g=g_cost
            child.h=h_cost
            child.f=f_cost
            flag1=0
            flag2=0
            for i in range(len(open_list)):
                if child.position==open_list[i].position:
                    flag1=1
                    index1=i
                    break
            
            for i in range(len(closed_list)):
                if child.position==closed_list[i].position:
                    flag2=1
                    index2=i
                    break

            if(flag2==1):
                if(child.f<closed_list[index2].f):
                    closed_list[index2]=child
            elif(flag1==1):
                if(child.f<open_list[index1].f):
                    open_list[index1]=child
            else:
                open_list.append(child) 
        
        closed_list.append(parent)

In [8]:
def path_generation(path):
    path_list_rev=[]
    path_list=[]
    while 1:
        path_list_rev.append(path.position)
        path=path.parent
        if path==None:
            break

    for i in range(len(path_list_rev)):
        path_list.append(path_list_rev[len(path_list_rev)-1-i])
    return path_list

In [9]:
def Draw_Horizontal(Array,Index1,Index2):   #Draws A horizontal Line from index1 to index2
	Local_Counter = Index1[1]
	while(Local_Counter <= Index2[1]):
		Array[Index1[0],Local_Counter]= 0
		Local_Counter+=1

In [10]:
def Draw_Vertical(Array,Index1,Index2):    #Draws A Vertical Line from index1 to index2
	Local_Counter = Index1[0]
	while(Local_Counter <= Index2[0]):
		Array[Local_Counter,Index1[1]]= 0
		Local_Counter+=1

In [32]:
def Draw(Map):    #Draws a Map
    draw_counter=0
    global x,y
    Draw_Horizontal(Map,[0,0],[0,y-1])
    Draw_Horizontal(Map,[x-1,0],[x-1,y-1])
    Draw_Vertical(Map,[0,0],[x-1,0])
    Draw_Vertical(Map,[0,y-1],[x-1,y-1])

    #Draw_Horizontal(Map,[2,0],[2,y-3]) ####trial boundaries  <-----------change these
    #Draw_Horizontal(Map,[4,2],[4,y-1]) ####trial boundaries      to change bounderies or
    #Draw_Horizontal(Map,[6,0],[6,y-3]) ####trial boundaries      add other bounderies as you like.
    #Draw_Horizontal(Map,[8,2],[8,y-1]) ####trial boundaries       <------------
    #Draw_Vertical(Map,[2,y-3],[6,y-3])
    #Draw_Vertical(Map,[0,y-1],[x-1,y-1])
    #Draw_Vertical(Map,[4,2],[x-3,2])
    

In [33]:
x = 11      #<-----------------
y = 11      #<-----------------
start=node_class([1,1],0,0,0,None,2)  #position,g,h,f,parent      #<-----------------
goal=node_class([9,9],0,0,0,None,3)               #<-----------------
Map = np.ones((x,y))
Draw(Map)
Map[start.position[0],start.position[1]]=start.type
Map[goal.position[0],goal.position[1]]=goal.type
print(Map)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
path = A_star(start,goal)
final_path=path_generation(path)
final_path.pop(0)
final_path.pop(-1)
for i in final_path:
	Map[i[0],i[1]]=88

print(Map)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 88.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1. 88.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1. 88.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1. 88.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1. 88.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1. 88.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1. 88.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
